# Generated by Django 3.1.7 on 2021-03-20 23:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='women',
            old_name='imagen',
            new_name='image',
        ),
    ]
